# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0003_remove_show_ttl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='copyright',
            field=models.CharField(blank=True, help_text="Organization name; &copy; and 2017 will be prepended automatically; if blank, uses show's title", max_length=255, verbose_name='copyright'),
        ),
    ]
