# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 05:13
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0004_auto_20170917_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
