# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 05:22
from __future__ import unicode_literals

from django.db import migrations
import uuid


def gen_guid(apps, schema_editor):
    Episode = apps.get_model('podcast', 'Episode')
    for row in Episode.objects.all():
        row.guid = uuid.uuid4()
        row.save(update_fields=['guid'])


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0005_episode_guid'),
    ]

    operations = [
        migrations.RunPython(gen_guid, reverse_code=migrations.RunPython.noop),
    ]
