# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 22:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0006_auto_20170920_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='summary',
            new_name='notes',
        ),
    ]
