# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0007_auto_20170920_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='notes',
            field=models.TextField(blank=True, help_text='Max length of 4,000 characters; accepts &lt;p&gt; &lt;ol&gt; &lt;ul&gt; &lt;li&gt; &lt;a&gt; &lt;em&gt; &lt;i&gt; &lt;b&gt; &lt;strong&gt;; if blank, uses description', max_length=4000, verbose_name='notes'),
        ),
    ]
