# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 01:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0008_auto_20170920_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='subtitle',
            new_name='summary',
        ),
    ]
