# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0009_auto_20170923_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='summary',
            field=models.CharField(blank=True, help_text='A single, descriptive sentence of the episode', max_length=255, verbose_name='summary'),
        ),
    ]
