# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0011_episode_itunes_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='type',
            field=models.CharField(choices=[('full', 'Full'), ('trailer', 'Trailer'), ('bonus', 'Bonus')], default='full', help_text='Full is for episodes, trailer is for promotional previews, and bonus is for extra content', max_length=255, verbose_name='type'),
        ),
    ]
