# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0015_show_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='guid',
            field=models.CharField(editable=False, max_length=64, verbose_name='GUID'),
        ),
    ]
