# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0016_auto_20170923_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='itunes',
            field=models.URLField(blank=True, help_text='Paste iTunes URL here after submission of show feed URL to <a href="https://podcastsconnect.apple.com/">iTunes Connect</a>', verbose_name='iTunes URL'),
        ),
    ]
