# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0017_auto_20170923_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='subtitle',
            field=models.CharField(help_text='A single, descriptive sentence of the show', max_length=255, verbose_name='subtitle'),
        ),
    ]
